apiVersion: apps/v1
kind: Deployment
metadata:
  name: astredis
  labels:
    app: astredis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: astredis
  template:
    metadata:
      labels:
        app: astredis
    spec:
      containers:
      - name: astridcloudcanister
        image: cloud.canister.io:5000/arhturescriou/node-redis
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: '6379'
          - name: REDIS_URL
            value: 'redis://10.3.190.135:6379'
      imagePullSecrets:
        - name: regcred